{"stream": {"cluster_log_level": "infra-logs", "k8s_namespace_name": "openshift-etcd", "openshift_cluster": "moc/smaug"}, "values": [["1656092417281000000", "{\"docker.container_id\":\"5e2e397d96854a232f22c9a2d50f983e10eabee231d82bd7916c9e7f1afa46b1\",\"kubernetes.container_image\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_image_id\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_name\":\"etcd-metrics\",\"kubernetes.host\":\"oct-10-04-control\",\"kubernetes.labels.app\":\"etcd\",\"kubernetes.labels.etcd\":\"true\",\"kubernetes.labels.k8s-app\":\"etcd\",\"kubernetes.labels.revision\":\"7\",\"kubernetes.master_url\":\"https://kubernetes.default.svc\",\"kubernetes.namespace_id\":\"c2307886-91a6-4d75-a112-ecdbd86ae0ed\",\"kubernetes.namespace_labels.kubernetes_io/metadata_name\":\"openshift-etcd\",\"kubernetes.namespace_labels.openshift_io/run-level\":\"0\",\"kubernetes.namespace_name\":\"openshift-etcd\",\"kubernetes.pod_id\":\"a6c518d6-c82b-4a3f-99e2-251f9c0dcf4c\",\"kubernetes.pod_ip\":\"128.52.62.187\",\"kubernetes.pod_name\":\"etcd-oct-10-04-control\",\"message\":\"{\\\"level\\\":\\\"warn\\\",\\\"ts\\\":\\\"2022-06-24T17:40:17.281Z\\\",\\\"caller\\\":\\\"zapgrpc/zapgrpc.go:191\\\",\\\"msg\\\":\\\"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \\\\\\\"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\\\\\\\". Reconnecting...\\\"}\",\"message_key\":null,\"offset\":504138709,\"partition\":2,\"source_type\":\"kafka\",\"topic\":\"smaug-prod.cluster-logs.infrastructure\"}"], ["1656092406052000000", "{\"docker.container_id\":\"3196092df38e8297283d10b65b96d24441ded928f5f7c5e5744901dfff49dcc4\",\"kubernetes.container_image\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_image_id\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_name\":\"etcd-metrics\",\"kubernetes.host\":\"oct-10-05-control\",\"kubernetes.labels.app\":\"etcd\",\"kubernetes.labels.etcd\":\"true\",\"kubernetes.labels.k8s-app\":\"etcd\",\"kubernetes.labels.revision\":\"7\",\"kubernetes.master_url\":\"https://kubernetes.default.svc\",\"kubernetes.namespace_id\":\"c2307886-91a6-4d75-a112-ecdbd86ae0ed\",\"kubernetes.namespace_labels.kubernetes_io/metadata_name\":\"openshift-etcd\",\"kubernetes.namespace_labels.openshift_io/run-level\":\"0\",\"kubernetes.namespace_name\":\"openshift-etcd\",\"kubernetes.pod_id\":\"73bf8ac7-f84e-4cdf-8388-76146356c7e0\",\"kubernetes.pod_ip\":\"128.52.62.137\",\"kubernetes.pod_name\":\"etcd-oct-10-05-control\",\"message\":\"{\\\"level\\\":\\\"warn\\\",\\\"ts\\\":\\\"2022-06-24T17:40:06.052Z\\\",\\\"caller\\\":\\\"zapgrpc/zapgrpc.go:191\\\",\\\"msg\\\":\\\"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \\\\\\\"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\\\\\\\". Reconnecting...\\\"}\",\"message_key\":null,\"offset\":504138301,\"partition\":2,\"source_type\":\"kafka\",\"topic\":\"smaug-prod.cluster-logs.infrastructure\"}"], ["1656092403635000000", "{\"docker.container_id\":\"37e8780711f910a9ca9e1136d4f5ea2fac39e628296a652f299c7f578a61e5d2\",\"kubernetes.container_image\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_image_id\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_name\":\"etcd-metrics\",\"kubernetes.host\":\"oct-10-06-control\",\"kubernetes.labels.app\":\"etcd\",\"kubernetes.labels.etcd\":\"true\",\"kubernetes.labels.k8s-app\":\"etcd\",\"kubernetes.labels.revision\":\"7\",\"kubernetes.master_url\":\"https://kubernetes.default.svc\",\"kubernetes.namespace_id\":\"c2307886-91a6-4d75-a112-ecdbd86ae0ed\",\"kubernetes.namespace_labels.kubernetes_io/metadata_name\":\"openshift-etcd\",\"kubernetes.namespace_labels.openshift_io/run-level\":\"0\",\"kubernetes.namespace_name\":\"openshift-etcd\",\"kubernetes.pod_id\":\"54ff6589-27f1-49d2-95da-8907e5b7b6fe\",\"kubernetes.pod_ip\":\"128.52.62.253\",\"kubernetes.pod_name\":\"etcd-oct-10-06-control\",\"message\":\"{\\\"level\\\":\\\"warn\\\",\\\"ts\\\":\\\"2022-06-24T17:40:03.636Z\\\",\\\"caller\\\":\\\"zapgrpc/zapgrpc.go:191\\\",\\\"msg\\\":\\\"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \\\\\\\"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\\\\\\\". Reconnecting...\\\"}\",\"message_key\":null,\"offset\":504138244,\"partition\":2,\"source_type\":\"kafka\",\"topic\":\"smaug-prod.cluster-logs.infrastructure\"}"], ["1656092301037000000", "{\"docker.container_id\":\"5e2e397d96854a232f22c9a2d50f983e10eabee231d82bd7916c9e7f1afa46b1\",\"kubernetes.container_image\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_image_id\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_name\":\"etcd-metrics\",\"kubernetes.host\":\"oct-10-04-control\",\"kubernetes.labels.app\":\"etcd\",\"kubernetes.labels.etcd\":\"true\",\"kubernetes.labels.k8s-app\":\"etcd\",\"kubernetes.labels.revision\":\"7\",\"kubernetes.master_url\":\"https://kubernetes.default.svc\",\"kubernetes.namespace_id\":\"c2307886-91a6-4d75-a112-ecdbd86ae0ed\",\"kubernetes.namespace_labels.kubernetes_io/metadata_name\":\"openshift-etcd\",\"kubernetes.namespace_labels.openshift_io/run-level\":\"0\",\"kubernetes.namespace_name\":\"openshift-etcd\",\"kubernetes.pod_id\":\"a6c518d6-c82b-4a3f-99e2-251f9c0dcf4c\",\"kubernetes.pod_ip\":\"128.52.62.187\",\"kubernetes.pod_name\":\"etcd-oct-10-04-control\",\"message\":\"{\\\"level\\\":\\\"warn\\\",\\\"ts\\\":\\\"2022-06-24T17:38:21.037Z\\\",\\\"caller\\\":\\\"zapgrpc/zapgrpc.go:191\\\",\\\"msg\\\":\\\"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \\\\\\\"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\\\\\\\". Reconnecting...\\\"}\",\"message_key\":null,\"offset\":693985384,\"partition\":1,\"source_type\":\"kafka\",\"topic\":\"smaug-prod.cluster-logs.infrastructure\"}"], ["1656092290903000000", "{\"docker.container_id\":\"37e8780711f910a9ca9e1136d4f5ea2fac39e628296a652f299c7f578a61e5d2\",\"kubernetes.container_image\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_image_id\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_name\":\"etcd-metrics\",\"kubernetes.host\":\"oct-10-06-control\",\"kubernetes.labels.app\":\"etcd\",\"kubernetes.labels.etcd\":\"true\",\"kubernetes.labels.k8s-app\":\"etcd\",\"kubernetes.labels.revision\":\"7\",\"kubernetes.master_url\":\"https://kubernetes.default.svc\",\"kubernetes.namespace_id\":\"c2307886-91a6-4d75-a112-ecdbd86ae0ed\",\"kubernetes.namespace_labels.kubernetes_io/metadata_name\":\"openshift-etcd\",\"kubernetes.namespace_labels.openshift_io/run-level\":\"0\",\"kubernetes.namespace_name\":\"openshift-etcd\",\"kubernetes.pod_id\":\"54ff6589-27f1-49d2-95da-8907e5b7b6fe\",\"kubernetes.pod_ip\":\"128.52.62.253\",\"kubernetes.pod_name\":\"etcd-oct-10-06-control\",\"message\":\"{\\\"level\\\":\\\"warn\\\",\\\"ts\\\":\\\"2022-06-24T17:38:10.903Z\\\",\\\"caller\\\":\\\"zapgrpc/zapgrpc.go:191\\\",\\\"msg\\\":\\\"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \\\\\\\"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\\\\\\\". Reconnecting...\\\"}\",\"message_key\":null,\"offset\":693984909,\"partition\":1,\"source_type\":\"kafka\",\"topic\":\"smaug-prod.cluster-logs.infrastructure\"}"], ["1656092262699000000", "{\"docker.container_id\":\"3196092df38e8297283d10b65b96d24441ded928f5f7c5e5744901dfff49dcc4\",\"kubernetes.container_image\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_image_id\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_name\":\"etcd-metrics\",\"kubernetes.host\":\"oct-10-05-control\",\"kubernetes.labels.app\":\"etcd\",\"kubernetes.labels.etcd\":\"true\",\"kubernetes.labels.k8s-app\":\"etcd\",\"kubernetes.labels.revision\":\"7\",\"kubernetes.master_url\":\"https://kubernetes.default.svc\",\"kubernetes.namespace_id\":\"c2307886-91a6-4d75-a112-ecdbd86ae0ed\",\"kubernetes.namespace_labels.kubernetes_io/metadata_name\":\"openshift-etcd\",\"kubernetes.namespace_labels.openshift_io/run-level\":\"0\",\"kubernetes.namespace_name\":\"openshift-etcd\",\"kubernetes.pod_id\":\"73bf8ac7-f84e-4cdf-8388-76146356c7e0\",\"kubernetes.pod_ip\":\"128.52.62.137\",\"kubernetes.pod_name\":\"etcd-oct-10-05-control\",\"message\":\"{\\\"level\\\":\\\"warn\\\",\\\"ts\\\":\\\"2022-06-24T17:37:42.699Z\\\",\\\"caller\\\":\\\"zapgrpc/zapgrpc.go:191\\\",\\\"msg\\\":\\\"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \\\\\\\"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\\\\\\\". Reconnecting...\\\"}\",\"message_key\":null,\"offset\":504132422,\"partition\":2,\"source_type\":\"kafka\",\"topic\":\"smaug-prod.cluster-logs.infrastructure\"}"], ["1656092194209000000", "{\"docker.container_id\":\"37e8780711f910a9ca9e1136d4f5ea2fac39e628296a652f299c7f578a61e5d2\",\"kubernetes.container_image\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_image_id\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_name\":\"etcd-metrics\",\"kubernetes.host\":\"oct-10-06-control\",\"kubernetes.labels.app\":\"etcd\",\"kubernetes.labels.etcd\":\"true\",\"kubernetes.labels.k8s-app\":\"etcd\",\"kubernetes.labels.revision\":\"7\",\"kubernetes.master_url\":\"https://kubernetes.default.svc\",\"kubernetes.namespace_id\":\"c2307886-91a6-4d75-a112-ecdbd86ae0ed\",\"kubernetes.namespace_labels.kubernetes_io/metadata_name\":\"openshift-etcd\",\"kubernetes.namespace_labels.openshift_io/run-level\":\"0\",\"kubernetes.namespace_name\":\"openshift-etcd\",\"kubernetes.pod_id\":\"54ff6589-27f1-49d2-95da-8907e5b7b6fe\",\"kubernetes.pod_ip\":\"128.52.62.253\",\"kubernetes.pod_name\":\"etcd-oct-10-06-control\",\"message\":\"{\\\"level\\\":\\\"warn\\\",\\\"ts\\\":\\\"2022-06-24T17:36:34.210Z\\\",\\\"caller\\\":\\\"zapgrpc/zapgrpc.go:191\\\",\\\"msg\\\":\\\"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \\\\\\\"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\\\\\\\". Reconnecting...\\\"}\",\"message_key\":null,\"offset\":693980627,\"partition\":1,\"source_type\":\"kafka\",\"topic\":\"smaug-prod.cluster-logs.infrastructure\"}"], ["1656092180815000000", "{\"docker.container_id\":\"5e2e397d96854a232f22c9a2d50f983e10eabee231d82bd7916c9e7f1afa46b1\",\"kubernetes.container_image\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_image_id\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_name\":\"etcd-metrics\",\"kubernetes.host\":\"oct-10-04-control\",\"kubernetes.labels.app\":\"etcd\",\"kubernetes.labels.etcd\":\"true\",\"kubernetes.labels.k8s-app\":\"etcd\",\"kubernetes.labels.revision\":\"7\",\"kubernetes.master_url\":\"https://kubernetes.default.svc\",\"kubernetes.namespace_id\":\"c2307886-91a6-4d75-a112-ecdbd86ae0ed\",\"kubernetes.namespace_labels.kubernetes_io/metadata_name\":\"openshift-etcd\",\"kubernetes.namespace_labels.openshift_io/run-level\":\"0\",\"kubernetes.namespace_name\":\"openshift-etcd\",\"kubernetes.pod_id\":\"a6c518d6-c82b-4a3f-99e2-251f9c0dcf4c\",\"kubernetes.pod_ip\":\"128.52.62.187\",\"kubernetes.pod_name\":\"etcd-oct-10-04-control\",\"message\":\"{\\\"level\\\":\\\"warn\\\",\\\"ts\\\":\\\"2022-06-24T17:36:20.815Z\\\",\\\"caller\\\":\\\"zapgrpc/zapgrpc.go:191\\\",\\\"msg\\\":\\\"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \\\\\\\"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\\\\\\\". Reconnecting...\\\"}\",\"message_key\":null,\"offset\":693980090,\"partition\":1,\"source_type\":\"kafka\",\"topic\":\"smaug-prod.cluster-logs.infrastructure\"}"], ["1656092133308000000", "{\"docker.container_id\":\"3196092df38e8297283d10b65b96d24441ded928f5f7c5e5744901dfff49dcc4\",\"kubernetes.container_image\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_image_id\":\"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17e87b4db7b34cfb48f42cae353ada3146bf45875ef65684a402610f97044133\",\"kubernetes.container_name\":\"etcd-metrics\",\"kubernetes.host\":\"oct-10-05-control\",\"kubernetes.labels.app\":\"etcd\",\"kubernetes.labels.etcd\":\"true\",\"kubernetes.labels.k8s-app\":\"etcd\",\"kubernetes.labels.revision\":\"7\",\"kubernetes.master_url\":\"https://kubernetes.default.svc\",\"kubernetes.namespace_id\":\"c2307886-91a6-4d75-a112-ecdbd86ae0ed\",\"kubernetes.namespace_labels.kubernetes_io/metadata_name\":\"openshift-etcd\",\"kubernetes.namespace_labels.openshift_io/run-level\":\"0\",\"kubernetes.namespace_name\":\"openshift-etcd\",\"kubernetes.pod_id\":\"73bf8ac7-f84e-4cdf-8388-76146356c7e0\",\"kubernetes.pod_ip\":\"128.52.62.137\",\"kubernetes.pod_name\":\"etcd-oct-10-05-control\",\"message\":\"{\\\"level\\\":\\\"warn\\\",\\\"ts\\\":\\\"2022-06-24T17:35:33.309Z\\\",\\\"caller\\\":\\\"zapgrpc/zapgrpc.go:191\\\",\\\"msg\\\":\\\"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \\\\\\\"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\\\\\\\". Reconnecting...\\\"}\",\"message_key\":null,\"offset\":693977988,\"partition\":1,\"source_type\":\"kafka\",\"topic\":\"smaug-prod.cluster-logs.infrastructure\"}"]]}